### ISSUE TITLE
Use the bot to ban/unban users

### ISSUE THREAD

**Issue by williamkapke** [nodejs/github-bot#106]
A `ban.json` file to be added to the moderation repo (migrate existing list) in this format:
```js
{
  //userid-username: [ start - end, ... ]
  "1234-ghost": [ "2016-12-14 to 2017-12-14" ],
  "100934-foobarbaz": [ "2015-01-28 to 2016-01-28" ]
}
```
<sup>* the goal of this file is to have an extremely simple format even though it causes extra parsing for the bot</sup>
<sup>* username is there just for human convenience</sup>
To automate lifting bans; the bot will sync the file with the Org's bans once a day.

Workflow to ban a user:
- A member of the org creates a PR to the `bans.json` file. This can just be a proposal for a ban and a thread to discuss.
- Once X number of collaborators approve the PR, the bot merges it. (X to be determined by policy)
- When the bot gets a notification that this file has been changed (for any reason), it will sync the Org's bans with the list - adding any new bans or lifting any removed/expired bans.

**Comment by Fishrock123** [comment]
This requires Owner permissions IIRC.

**Comment by targos** [comment]
I can't find a reference to user blocking in the GitHub API docs. Are you sure it's possible?

**Comment by williamkapke** [comment]
... which the bot is supposed to have at this point. Does it not?

**Comment by williamkapke** [comment]
@targos oooohhh... good point. Maybe this ISN'T possible :(

**Comment by Fishrock123** [comment]
> ... which the bot is supposed to have at this point. Does it not?

No, the discussion was to approve that for a separate, restricted bot, no?

**Comment by williamkapke** [comment]
@Fishrock123 It was completed here: https://github.com/nodejs/github-bot/issues/72#issuecomment-249387202
... I guess that issue could be closed

**Comment by Fishrock123** [comment]
Oh right, it turns out there are specific permissions for that. We'd have to find out if the block list is accessible by the API.

**Comment by bnoordhuis** [comment]
Handing admin rights, even if scoped, to a script that runs unsupervised for most of the day gives me the willies.  What are the failure modes for hostile attacks, software bugs and bad input?

**Comment by phillipj** [comment]
FYI I sent a question to GitHub Support whether or not it's possible to block users via their API.

**Comment by phillipj** [comment]
> Hi, Phillip,
> 
> You're not missing anything -- the ability to block users is not exposed via the API currently. It's something we're considering for the future, but I can't promise when it will happen.
> 
> Thanks for expressing interest in this, and if there's anything else you'd like to see improved -- please let us know.
> 
> Cheers,
> Ivan

In other words, not much the bot can do ATM.

**Comment by williamkapke** [comment]
@phillipj GAH! What a major snag to this plan! Thanks a million for asking them.

The SFNode meetup is at GitHub next month (Jan 5th I think)... I'll see if I can ask around more there.

**Comment by phillipj** [comment]
Closing this for now as it seems we're out of luck until GitHub exposes ban/unban via their API.

**Comment by phillipj** [comment]
Re-opening this as I just got a follow up email from GitHub staff. They have added support for block/unblocking users:

- https://developer.github.com/v3/orgs/blocking/
- https://developer.github.com/v3/users/blocking/

And a webhook which might come in handy:

- https://developer.github.com/v3/activity/events/types/#orgblockevent

**Comment by MylesBorins** [comment]
🎉

**Comment by phillipj** [comment]
@williamkapke is this something your newly created https://github.com/williamkapke/orgbot could handle?

**Comment by williamkapke** [comment]
indeed it does!

**Comment by phillipj** [comment]
Oooh nice, lets close this (again) in favor of the new rockstar in town: https://github.com/williamkapke/orgbot

**Comment by williamkapke** [comment]
heh, well that "rockstar" isn't getting a very positive reception (yet?):
https://github.com/nodejs/community-committee/issues/22

We'll just need to wait and see if anyone changes their mind I guess.

**Comment by phillipj** [comment]
Thanks for the reference, an interesting discussion I wasn't aware of.
