### ISSUE TITLE
Automatic github API retry

### ISSUE THREAD

**Issue by mscdex** [nodejs/github-bot#121]
Ref https://github.com/nodejs/node/pull/11081#issuecomment-276460362. When Github responds with 404 or other unexpected status codes, the bot should retry x times in some period of time instead of giving up after one failed attempt.

**Comment by phillipj** [comment]
Closing this as the mentioned comment was related to retrying fetching files on 404 from github, that landed with https://github.com/nodejs/github-bot/pull/130.
