### ISSUE TITLE
Replacing 'checkboxes' in github templates

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/github-bot#122]
It would be awesome if we could move towards replacing our checkboxes in PR's by looking at the commit and providing that feedback differently.

We already do some similar stuff by tagging. A few of the things mentioned in this issue is obviously out of scope - but I felt that describing my perceived future would make it easier to understand the changes/features I'm suggesting.

I guess the discussion about checkboxes is tangential with user feedback in general, but by looking github interprets checkboxes/messages (poor formatting as part of timelines, adds progress to issue listings, etc) I feel that what we want to identify might as well work a bit differently. We could for instance:

- spawn a bot that identifies that changes are made/introduced but lacks a test
- spawn a benchmark if it touches related benchmarks
- run remarkrc on documentation if it is updated

Finally, we can run the commit message validator once we've deemed it 'ready' to merge (commit message metadata, properly rebased, all other tests merge).

I guess the final (and future) step is the long awaited auto-merge; which also could grow the functionality of adding PR/Reviewed-by references.

..all of above could be reported through the testing section. I'm personally not a big fan of abusing comments for bot input/output since it can potentially ping a lot of people.

**Comment by targos** [comment]
+1 for using the testing section for this feedback. Is there a limit on the number of checks that you can add in a PR?

**Comment by jbergstroem** [comment]
@targos I recall a number large enough to not really care. In time, we'll likely fold all the platform tests into one output as well.

**Comment by Trott** [comment]
Checkboxes are gone from the template for some time at this point. We also have a GitHub Action running remark-lint but we don't have autodetection of missing tests (although we might have automated coverage reporting that leaves a comment if coverage decreases by more than a threshold).
