### ISSUE TITLE
Bot labelled nodejs/node#11583 as meta

### ISSUE THREAD

**Issue by gibfahn** [nodejs/github-bot#127]
The bot added the `meta` label to https://github.com/nodejs/node/pull/11583, which as far as I can see didn't touch any of the files specified in [lib/node-labels.js#L10-L11](https://github.com/nodejs/github-bot/blob/master/lib/node-labels.js#L10-L11), which is:

```js
  [/^([A-Z]+$|CODE_OF_CONDUCT|ROADMAP|WORKING_GROUPS|GOVERNANCE|CHANGELOG|\.mail|\.git.+)/, 'meta'],
```

AFAICT this matches `ALLCAPS` or something that starts with one of the listed words in the root.

Looks like `meta` labelling was added in https://github.com/nodejs/github-bot/pull/37 so cc/ @Fishrock123 

<br/>

### Files in nodejs/node#11583:

![image](https://cloud.githubusercontent.com/assets/15943089/23579945/4b738046-00f0-11e7-95c1-0cd656fb5474.png)

**Comment by Fishrock123** [comment]
I actually have no idea.

I believe your understanding of the `meta` regex is correct.

**Comment by mscdex** [comment]
All I can go by right now is the current changes in the PR (Github complains about too many requests if I try to go back 23 days in the repo's webhook logs), so AFAICT it's working as expected. That PR (currently) contains changes to these files that get matched in the regexp:

* AUTHORS
* WORKING_GROUPS.md

**Comment by gibfahn** [comment]
@mscdex the PR now needs a rebase, so I'm sure it does contain changes to those files, it certainly didn't when I opened this issue. Maybe it also did originally too (when the bot added the labels).

**Comment by phillipj** [comment]
Sounds like there's some chance this actually worked as expected, and sadly not possible to find the list of changed files *at the exact moment* the bot labelled the PR.

Logging everything that happens on a PR would have come in handy: https://github.com/nodejs/github-bot/issues/73

Closing this for now as it seems more or less impossible to have the facts for digging deeper here.
