### ISSUE TITLE
jenkins: triggering build by comment fails

### ISSUE THREAD

**Issue by phillipj** [nodejs/github-bot#146]
Bot has started failing when a repository collaborator posts a comment trying to trigger Jenkins builds. 

Seeing 403 responses from Jenkins:
```bash
14:29:58.319Z  INFO bot: Emitting GitHub event (req_id=9a72f191-0b2d-43bd-bed5-da166834054e, pr=nodejs/citgm/#402, action=issue_comment.created)
14:29:58.499Z DEBUG bot: Triggering Jenkins build (req_id=9a72f191-0b2d-43bd-bed5-da166834054e, pr=nodejs/citgm/#402, action=issue_comment.created)
14:29:58.777Z ERROR bot: Error while triggering Jenkins build (req_id=9a72f191-0b2d-43bd-bed5-da166834054e, pr=nodejs/citgm/#402, action=issue_comment.created)
    Error: Expected 201 from Jenkins, got 403
```

I have verified both Jenkins tokens needed are correct: bot account API token and remote auth token for the [citgm-continuous-integration-pipeline](https://ci.nodejs.org/view/Node.js-citgm/job/citgm-continuous-integration-pipeline) build. Those tokens has not changed since deploying this functionality and it was verified to work back then.

Not sure what could be the cause of sudden 403s. Has Jenkins been updated lately @nodejs/build?

Refs https://github.com/nodejs/citgm/pull/402#issuecomment-305978388

**Comment by gibfahn** [comment]
The earliest failure I can find is May 1 https://github.com/nodejs/citgm/pull/402#issuecomment-298440189), and the last good run I can find is 
April 25 https://github.com/nodejs/citgm/pull/400#issuecomment-297067746.

I'd assume the most likely culprit is a plugin update, presumably one of the Github ones

Current versions are (note that the number on the left is the installed version, the one on the right is the available update):

![image](https://user-images.githubusercontent.com/15943089/26972361-6327e6b8-4d09-11e7-8894-68a5a6502a52.png)

**Comment by gibfahn** [comment]
https://github.com/nodejs/citgm/pull/553#issuecomment-380817232

Seems to be going well

**Comment by BridgeAR** [comment]
:tada: that is awesome! So this issue seems fixed and we can move forward, right?

**Comment by gibfahn** [comment]
>🎉 that is awesome! So this issue seems fixed and we can move forward, right?

Looks like it. I'll close this for now, we can continue the discussion in https://github.com/nodejs/build/issues/1180
