### ISSUE TITLE
Some jenkins jobs failed to push state.

### ISSUE THREAD

**Issue by starkwang** [nodejs/github-bot#163]
It seems that some of our jenkins jobs failed to push state to Github, especially these jobs named like `node-test-linux-linked-xxx`:

Some PRs containing pending jobs for a long time: 
https://github.com/nodejs/node/pull/17907#partial-pull-merging
https://github.com/nodejs/node/pull/17908#partial-pull-merging

Recently there is almost **no** CI-passed PR so it's better to fix it as fast as we can.

**Comment by maclover7** [comment]
Moving this to https://github.com/nodejs/build/issues/1053

(@starkwang no worries, in general we try and keep Jenkins incidents / infrastructure issues logged at the nodejs/build repo)

**Comment by starkwang** [comment]
Closed due to https://github.com/nodejs/build/pull/1054
