### ISSUE TITLE
Add dont-land-on-v6.x and v8.x labels for ES Modules PRs

### ISSUE THREAD

**Issue by gibfahn** [nodejs/github-bot#164]
I'm not sure if this is possible, but if someone adds the `ES Modules` label, the bot should add the dont-land-on labels.

e.g. https://github.com/nodejs/node/pull/17786

cc/ @MylesBorins

**Comment by MylesBorins** [comment]
should they be `don't land` for 8.x?

**Comment by gibfahn** [comment]
Sorry, bad grammar, I meant dont-land-on for v6.x and v8.x

i.e. dont-land-on-v{6,8}.x

**Comment by joyeecheung** [comment]
The bot should be able to add the `ES Modules` label by itself anyway.

**Comment by richardlau** [comment]
This can be closed as Node.js 6 and 8 are End-of-Life.
