### ISSUE TITLE
Using the bot for autodeploying docker

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/github-bot#170]
Hey All,

can ya take a look at https://github.com/nodejs/docker-node/pull/672

**Comment by phillipj** [comment]
Thanks for the ping 👍

I've done a couple of things to help that moving forward: https://github.com/nodejs/docker-node/issues/670#issuecomment-378206904

**Comment by phillipj** [comment]
Closing this since it has been working for a while now as far as I've understood.
