### ISSUE TITLE
Use ngrok over hook_relay

### ISSUE THREAD

**Issue by ryzokuken** [nodejs/github-bot#172]
Right now, we're using a simple SSE_RELAY script from https://github.com/williamkapke/hook-relay in order to develop the bot locally, which requires setup and running a heroku instance and what not, while the script might be the best alternative when we made that decision, it stands unmaintained and unsupported in any way officially.

ngrok (https://ngrok.com/) is a cool utility that allows you to skip a lot of that setup and loggin-in and running whatnot, and is mentioned in GitHub's official docs, it also seems well-maintained.

**Comment by phillipj** [comment]
Although I haven't used ngrok before, I don't hesitate it could be a better option than what we have today with the SSE_RELAY.

If I recall correctly, the reason we introduced SSE_RELAY in the first place were to get webhook events triggered locally from an actual repository on github.com, without having to add a custom webhook pointing to ourselfs.

An example of that would be the [TestOrgPleaseIgnore/node](https://github.com/TestOrgPleaseIgnore/node) which has the SSE_RELAY webhook in place. That allows us to open PRs, issues etc to that repo and get webhook events forwarded to us locally without adding a new webhook in that repository's settings. I assume the rationale was that's (1) convenient and (2) not everyone has enough privileges to add such a custom webhook pointing to themselfs.

Would using ngrok work the same way? Maybe you could reference the official GitHub docs you're referring to?

**Comment by ryzokuken** [comment]
Official docs: https://developer.github.com/webhooks/configuring/

**Comment by ryzokuken** [comment]
> An example of that would be the TestOrgPleaseIgnore/node which has the SSE_RELAY webhook in place. That allows us to open PRs, issues etc to that repo and get webhook events forwarded to us locally without adding a new webhook in that repository's settings. I assume the rationale was that's (1) convenient and (2) not everyone has enough privileges to add such a custom webhook pointing to themselfs.

@phillipj wait, let me get this straight... No matter where you host the SSE_RELAY, the webhook will be sent there without changing the settings inside the repository? No, that's not how I'm using ngrok at the moment. Everytime I run ngrok again and am assigned a URL, I set that again in the settings manually. If that's the case with SSE_RELAY, then it might just be a better option than ngrok.

**Comment by phillipj** [comment]
Yeah, that's what have tried to communicate in the [Developing Locally](https://github.com/nodejs/github-bot#developing-locally) section of the README, but I'm sure we could have rephrased it a little.

Any suggestions to that part of the README is more than welcome.

I'm closing this for now as it sounds like ngrok won't help us much compared to what SSE_RELAY does today, feel free to re-open if I've misunderstood.

**Comment by ryzokuken** [comment]
@phillipj you're right. I realized this myself too. The way SSE_RELAY works is just way too convenient for us to swap it out. I've been using ngrok at nodejs/badges, but I'll try migrating to SSE_RELAY too.
