### ISSUE TITLE
Automatic redeploy on merge is broken

### ISSUE THREAD

**Issue by phillipj** [nodejs/github-bot#185]
Yesterday while merging https://github.com/nodejs/github-bot/pull/183 there were no traces of the bot redeploying.

Looking at the webhook we have setup in this repo that pushes info about git pushes on github.com to our bot server, says the HTTP request sent was successfully delivered. That gives me the impression that something is not working on the bot server's end.

I haven't had time to dig deep into this yet, but creating this issue before I forget. Also referencing the newly migrated and applied ansible playbook in case that had any unexpected changes: https://github.com/nodejs/build/pull/1067

**Comment by maclover7** [comment]
Will take a look at this.

**Comment by maclover7** [comment]
Will be fixed via https://github.com/nodejs/github-bot/pull/186 and https://github.com/nodejs/build/pull/1382

**Comment by phillipj** [comment]
That was quick, thanks! 👌
