### ISSUE TITLE
need to generate a Jenkins API new token

### ISSUE THREAD

**Issue by refack** [nodejs/github-bot#201]
New version of Jenkins revoked all API tokens.
https://ci.nodejs.org/user/nodejs-github-bot/configure

**Comment by richardlau** [comment]
> 
> 
> I don't have privileges do see those tokens anymore, so I can't help update them.
> 
> FYI all the secrets the bot gets provided as environment variables are defined in the secrets repo.

Is that a @nodejs/build-infra issue then?

**Comment by phillipj** [comment]
The ones who has read/write access to the github-bot secrets are a subset of the build WG, I'd ping @joyeecheung @maclover7 @rvagg.

For ref these secrets are defined in `build/github-bot/deployment_secrets.md` inside the secrets repo and used together with the [create-github-bot.yml](https://github.com/nodejs/build/blob/master/ansible/playbooks/create-github-bot.yml) playbook.

**Comment by refack** [comment]
BTW: that group might need a refresh - https://github.com/nodejs/build/pull/1575

**Comment by maclover7** [comment]
I can take a look at this in the next day or so

**Comment by refack** [comment]
Works: https://github.com/nodejs/node/pull/24538
