### ISSUE TITLE
sadly an error occured when I tried to trigger a build :(

### ISSUE THREAD

**Issue by richardlau** [nodejs/github-bot#210]
Looks like the bot hasn't been able to automatically start lite builds on collaborator submitted pull requests lately, e.g. https://github.com/nodejs/node/pull/25516#issuecomment-454433297, and reports:

> sadly an error occured when I tried to trigger a build :(

**Comment by phillipj** [comment]
Thanks for reporting! This might be related to some recent changes that got deployed last week. I'll double check the error logs for details later today.

**Comment by phillipj** [comment]
Found one error related to that PR:

```
16:29:25.344 ERROR bot: Error while triggering Jenkins build (req_id=56e73180-18da-11e9-8fbf-8bd7847363eb, pr=nodejs/node/#25516, action=pull_request.opened)
    TypeError: The header content contains invalid characters
        at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:359:11)
        at new ClientRequest (_http_client.js:85:14)
        at Object.exports.request (http.js:31:10)
        at Object.exports.request (https.js:206:15)
        at Object.request (/home/iojs/github-bot/node_modules/agent-base/patch-core.js:23:20)
        at Request.start (/home/iojs/github-bot/node_modules/request/request.js:751:32)
        at Request.write (/home/iojs/github-bot/node_modules/request/request.js:1497:10)
        at end (/home/iojs/github-bot/node_modules/request/request.js:549:18)
        at Immediate.<anonymous> (/home/iojs/github-bot/node_modules/request/request.js:578:7)
        at runCallback (timers.js:672:20)
```

There's lots of other successful Jenkins -> GitHub updates before and after the above, so I'm assuming it's related to the PR somehow.

**Comment by richardlau** [comment]
Other recent failures (not exhaustive): 
https://github.com/nodejs/node/pull/25517#issuecomment-454434364
https://github.com/nodejs/node/pull/25510#issuecomment-454284982
https://github.com/nodejs/node/pull/25508#issuecomment-454252215
https://github.com/nodejs/node/pull/25507#issuecomment-454248441 
https://github.com/nodejs/node/pull/25472#issuecomment-453834575
https://github.com/nodejs/node/pull/25461#issuecomment-453716189 
https://github.com/nodejs/node/pull/25457#issuecomment-453688382

**Comment by phillipj** [comment]
Alrighty, #209 is now live in production. I'll remember to double check for these errors logs the next day.

**Comment by phillipj** [comment]
This looks promising:

```
19:42:45.235  INFO bot: Jenkins build started (req_id=58a89c50-18f5-11e9-a5d5-f9690fa1f072, pr=nodejs/node/#25523, action=pull_request.opened)
    buildUrl: https://ci.nodejs.org/blue/organizations/jenkins/node-test-pull-request-lite-pipeline/detail/node-test-pull-request-lite-pipeline/2257/pipeline
```

Closing this issue for now, feel free to re-open if I'm wrong :)

Refs https://github.com/nodejs/node/pull/25523
