### ISSUE TITLE
Post the CI link to the PR when a CI is started

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/github-bot#212]
Since human could forget to do this.

From a glance this should probably be done around https://github.com/nodejs/github-bot/blob/a76688e33fc1e274f3d8df35a0571750d0f11b7a/scripts/jenkins-status.js#L45-L49

**Comment by phillipj** [comment]
I'm all for automating all the things!

Think you're right about which lines to hook into.. We just gotta ensure we don't post comments about *all* jobs, called "checks" in GitHub UI (see below). I assume the job we should be filtering on is `node-test-pull-request`, right?

<img width="774" alt="Screen Shot 2019-03-20 at 21 51 06" src="https://user-images.githubusercontent.com/1231635/54718303-7e52b480-4b5a-11e9-9399-39e45f46fb03.png">

**Comment by joyeecheung** [comment]
@phillipj Yes, at least would could start from there.
