### ISSUE TITLE
`deprecations` label

### ISSUE THREAD

**Issue by vsemozhetbyt** [nodejs/github-bot#219]
Can we make the bot to add `deprecations` label automatically for all PRs that affect `doc/api/deprecations.md`?

**Comment by richardlau** [comment]
This is probably the most appropriate section to add it:
https://github.com/nodejs/github-bot/blob/02f69b8fd709d3c6b4a4b20d9267a0920313f730/lib/node-labels.js#L122-L128

with an appropriate test added to https://github.com/nodejs/github-bot/blob/master/test/unit/node-labels.test.js

**Comment by phillipj** [comment]
Closing this as #220 got merged and is alive in production 🎉
