### ISSUE TITLE
Provide a public api?

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/github-bot#26]
It'd be pretty sweet if we had a service that could provide simple badges that we can reuse throughout nodejs.org or on github (thinking really simple stuff here; ✅ or similar). I would for instance be interested in having a nightly job that runs against our different branches and reports test status as a badge, similar to how we nightly generate benchmarks. Once a simple api is in place we could expand this to collect other info that's relevant in the nodejs ecosystem. We for instance have a nightly coverity job that would be relevant to make more public or we could show a summary of issue/pr flow (open, closed -- ok, a simple emoji wouldn't work here).

I know this is borderline of what our bot should do, but it will likely have this information anyway. Thoughts?

**Comment by Fishrock123** [comment]
I think we'd probably want to have some sort of caching somewhere, this could induce a lot of request overhead if not done correctly.

Also, would it only be for the latest jobs, or would there be some history? This gets complex very quickly..

**Comment by maclover7** [comment]
This doesn't seem to be on the roadmap at this time, closing for now, please reopen if you would still like to work on this
