### ISSUE TITLE
Rename primary branch to main

### ISSUE THREAD

**Issue by mhdawson** [nodejs/github-bot#302]
We are going through all of the node.js repositories to rename the primary branch to main. Please see nodejs/node#33864 for more context.

There may need to be some changes outside the repository if anything references main specifically as a target for the github-bot. f that is the case we'd need to sync the rename and those changes outside the repository.

Could those more familiar with the github bot comment on that, or if we can just rename the primary branch to main without and other concerns.

**Comment by phillipj** [comment]
Sure thing, I'll double check the github-bot's code.

A recent PR in the node-pr-labeler action also comes to mind: https://github.com/nodejs/node-pr-labeler/pull/9. I'll dive into better alternatives.

**Comment by mhdawson** [comment]
@phillipj are you comfortable I can go ahead and do the rename now?

**Comment by phillipj** [comment]
@mhdawson yupp. Let's do it and just ping me directly if any thing seems weird after the fact.

The only thing I've got on my todo, is updating the auto deploy mechanisms in [nodejs/build/`github-bot-deploy-webhook.json.j2`](https://github.com/nodejs/build/blob/master/ansible/roles/github-bot/templates/github-bot-deploy-webhook.json.j2#L9) when commits lands into `github-bot/main` as opposed to `master`, but that's not a blocker in my eyes.

**Comment by mhdawson** [comment]
@phillipj thanks. Renamed, closing.
