### ISSUE TITLE
Access for Richard Lau

### ISSUE THREAD

**Issue by Trott** [nodejs/github-bot#335]
Richard Lau (@richardlau) does not apparently have access to the relevant secrets for the GitHub bot. Let's add him, please?

@nodejs/github-bot @nodejs/build

**Comment by richardlau** [comment]
I've had previous private discussions with @mhdawson (I think around the time we were renaming the branches from `master`->`main`) and we thought that probably everyone in @nodejs/build-infra probably ought to have access to all the secrets (including the github-bot) in the secrets repo.

**Comment by phillipj** [comment]
Sounds good to me 👍🏻

The list of people having access to those secrets would benefit from being revisited, that goes for the @nodejs/github-bot team too.

**Comment by Trott** [comment]
> The list of people having access to those secrets would benefit from being revisited, that goes for the @nodejs/github-bot team too.

I've gone ahead and removed maclover7 and williamkapke as they have both been absent from the core project for years, as far as I know. If there are others to be removed, let me know here or (if you prefer) privately. (My email is in my GitHub profile.)

If Richard wants to add himself to the team, he is an org owner and can do it himself, so I'll leave that alone either way.

**Comment by sxa** [comment]
From build WG meeting: @rvagg has access and will add the access for Richard

**Comment by richardlau** [comment]
Now sorted 🎉.
