### ISSUE TITLE
Add comment cc-ing teams/devs in issues

### ISSUE THREAD

**Issue by phillipj** [nodejs/github-bot#49]
It seems the auto labelling of node PRs has settled and working pretty good atm, are we ready to start cc-ing the sub-system maintainers?

Refs https://github.com/nodejs/node/pull/6694

/cc @Fishrock123

**Comment by phillipj** [comment]
Who to cc for reference: https://github.com/nodejs/node/blob/master/doc/onboarding-extras.md

**Comment by Trott** [comment]
This has been completed for some time. The bot pings based on CODEOWNERS content.
