### ISSUE TITLE
Monitor updates to pr and post Jenkins CI progress

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/github-bot#5]
Background and further details here: https://github.com/nodejs/build/issues/236

I'd be happy to chip in here.

**Comment by williamkapke** [comment]
@phillipj Looking at @jbergstroem's work for the build team in that linked issue above, I see he/they are using the [Github Status API](https://developer.github.com/v3/repos/statuses/). That seems like a cool way to go... maybe incorporate that in to the work you have in pollTravis?

**Comment by Fishrock123** [comment]
Yeah we should probably push to the github status API. That way, it also displays at the merge button and you don't need to find the latest comment.

**Comment by Fishrock123** [comment]
Related `github` module API: http://mikedeboer.github.io/node-github/#statuses, looking into it.

**Comment by phillipj** [comment]
@williamkapke trying to use to status API sounds awesome! One step closer to mimic Travis completely :dancers:

**Comment by Fishrock123** [comment]
moving the status api discussion to https://github.com/nodejs-github-bot/github-bot/issues/14

**Comment by phillipj** [comment]
@jbergstroem how would we know *when* to start polling? Could Jenkins do a HTTP requestagainst the bot, notifying there's a PR build that just started? Or should the bot listen for PR comments matching "CI: http://ci.nodejs.org/*"?

**Comment by jbergstroem** [comment]
I owe a few of you a post -- sorry for the delay. I'm a bit backlogged at the moment; will get back to you shortly.

**Comment by phillipj** [comment]
Seems the `../api/json` endpoint would be perfect for polling build status. E.g. for https://github.com/nodejs/node/pull/6342: https://ci.nodejs.org/job/node-test-pull-request/2363/api/json

**Comment by phillipj** [comment]
Landed with #35
