### ISSUE TITLE
Tagging first time contributors

### ISSUE THREAD

**Issue by jasnell** [nodejs/github-bot#56]
It would be helpful if the bot could help to identify new contributors to Node core by automatically tagging new PRs with a "New Contributor" label (if the user has never landed a commit in core) or "Recently New Contributor" label (if the user has only recently landed their first commit). This would make it easier to identify, welcome and recognize new contributors.

**Comment by phillipj** [comment]
I really like this idea! Do we want the bot to create a friendly comment as well?

**Comment by jasnell** [comment]
That would be good but I'd want to make sure collaborators are encouraged
to post their own welcome messages also.

**Comment by phillipj** [comment]
@jasnell has the need for this changed in some sense, now that GitHub does this? As seen in https://github.com/nodejs/node/pull/12727:
    
<img width="796" alt="screen shot 2017-05-06 at 12 52 31" src="https://cloud.githubusercontent.com/assets/1231635/25771786/94ef8692-325b-11e7-886a-4f04c67be581.png">

**Comment by jasnell** [comment]
Good question! I still think it's helpful but also better if the welcome message comes from a real person. I think we can close this!

**Comment by phillipj** [comment]
Alright, closing this then. Sorry for letting this rot forever...
