### ISSUE TITLE
Setup Travis CI

### ISSUE THREAD

**Issue by phillipj** [nodejs/github-bot#57]
Since the nodejs org doesn't allow 3rd party GH apps org wide access, we have to get Travis setup in a very weird way to get our PRs tested with Travis.

@Fishrock123 as you're the champion of semi-setup for Travis, you willing to help me on this?

**Comment by Fishrock123** [comment]
oh, _right_

**Comment by phillipj** [comment]
FYI for others, this is currently blocked due to security concerns mentioned in https://github.com/nodejs/help/issues/243.

**Comment by jbergstroem** [comment]
Also, we're currently experimenting with using our own Jenkins environment together with nvm to keep track of Node versions.

**Comment by Trott** [comment]
Done in https://github.com/nodejs/node/pull/21059.

**Comment by phillipj** [comment]
If I recall correctly, this issue was created to enable Travis in **this repo**. We've got lots of tests on the bot that would be great to have run as part of PRs, without us having to double check the branches before merging them 😞

**Comment by phillipj** [comment]
This has finally been resolved as we've transitioned from Travis CI as a GitHub service & polling hacks via the github-bot, to Travis CI GitHub app allowing us to provide Travis the access it needs per repo, not across the entire organisation.

Refs https://github.com/nodejs/github-bot/pull/183
