### ISSUE TITLE
Creating new labels?

### ISSUE THREAD

**Issue by jasnell** [nodejs/github-bot#58]
When I opened https://github.com/nodejs/node/pull/7972 which suggests adding a new internal module called `mapproxy`, the bot apparently went and proactively created a new label for it. Unfortunately, `mapproxy` is not an official thing and having such a label doesn't make sense yet.

**Comment by phillipj** [comment]
Good point, would be good to double check if the resolved labels actually
exists before adding them... At least for now as it has not intentionally
been made to create new labels like it just did
