### ISSUE TITLE
Add required Node.js Foundation documents

### ISSUE THREAD

**Issue by williamkapke** [nodejs/github-bot#59]
I will do a PR for this.

For more info see:
https://github.com/nodejs/TSC/issues/117
https://github.com/nodejs/post-mortem/issues/30

**Comment by phillipj** [comment]
Perfect! Sorry for not following along in the new repo/project discussion, but figured moving this was long overdue, so just made it happen :)

**Comment by williamkapke** [comment]
This is complete via #66
