### ISSUE TITLE
initial gh-bot meeting: 2016-09-07

### ISSUE THREAD

**Issue by Starefossen** [nodejs/github-bot#68]
I suggest we'll schedule a Bot Meeting to get this ball rolling. I also suggest we tag issues we would like to discuss with `wg-agenda` label or similar in the issue tracker.

Time: [16:00UTC Wednesday, 7 September 2016](http://www.timeanddate.com/worldclock/fixedtime.html?msg=gh-bot+meeting&iso=20160907T16&p1=%3A)
### Where
- [Event page](https://plus.google.com/u/1/b/100598160817214911030/events/c61883oa54k50a6v3c3d2dgrua0)
- [Participating](https://hangouts.google.com/call/mtwevqdnoretldu2gqmekqdipae)
- [Viewers](http://www.youtube.com/watch?v=3_H5u370wZE)
### Agenda
- Add required Node.js Foundation documents #59 (PR #66) 
- Open discussion about goals, ideas, scope
- Members/invite more members?
### Notes
- [Meeting notes](https://docs.google.com/document/d/1kwjcpwXt6YvCSY89Ll7ehn0DgygvagMxdrS7cVwGDqk/edit?usp=sharing)

**Comment by williamkapke** [comment]
It looks like this conflicts with a TSC meeting unfortunately. See: https://calendar.google.com/calendar/embed?src=kap.co_i17i575te0aes6kaanfjr2e4hs%40group.calendar.google.com

**Comment by Starefossen** [comment]
Thursday and Wednesday that week are my best days for me if we would like to get this meeting before Node.js Interactive. I can be very flexible on the time however.

**Comment by jbergstroem** [comment]
Can we do same time Wednesday?

**Comment by Starefossen** [comment]
@jbergstroem that would overlap with the CTC meeting according to the calendar.

**Comment by jbergstroem** [comment]
Ugh. Later Wednesday? Super keen on making it happen!

**Comment by Starefossen** [comment]
Later Wednesday could work for me.

**Comment by williamkapke** [comment]
I can do Wednesday after 2PM (PST).

Here's a doodle if it helps: http://doodle.com/poll/2kzmnapxgn79fqp6#table

/cc @nodejs/tsc

**Comment by williamkapke** [comment]
Last call? We should get this nailed down 😎

**Comment by jbergstroem** [comment]
Looks like Wednesday to me! @phillipj ?

**Comment by phillipj** [comment]
Afraid the upcoming week is pretty much booked for me :( Either do it w/o me which I'm sure you'll do just fine, or postpone at least another week.

**Comment by Starefossen** [comment]
I suggest we schedule a meeting for Wednesday even though Phillip will be unable to attend. Lets get the ball rolling and see where it lands.

**Comment by jbergstroem** [comment]
@Starefossen cool! Do you want to orchestrate this? I can set up the hangout/youtube links. I'll try to get down my thoughts into some document that doesn't make me sound delirious as well.

**Comment by Starefossen** [comment]
Sure, I can facilitate this meeting.

**Comment by jbergstroem** [comment]
@Starefossen could you update this issue with correct time/date? I will look at the hangouts stuff now.

**Comment by Fishrock123** [comment]
(Updated time & date)

**Comment by Starefossen** [comment]
Thanks @Fishrock123 👍🏼

**Comment by jbergstroem** [comment]
Apologies, url changed somehow. Participating url is https://hangouts.google.com/call/mtwevqdnoretldu2gqmekqdipae

**Comment by williamkapke** [comment]
It's been a long time since this meeting!

Will I see some of you at the Collab Summit in Berlin? Hope to chat!

**Comment by phillipj** [comment]
Will probably not be able to make it the Collab Summit, but I will be at JSConf EU the days after the summit.
