### ISSUE TITLE
Automatic bot deployment

### ISSUE THREAD

**Issue by phillipj** [nodejs/github-bot#69]
Now that the [ansible setup](https://github.com/nodejs/build/pull/469) has been created to setup host(s) for bot, my plan was to get it automatically deployed whenever new commits lands.

My thoughts so far has been to get some inspiration from the current [nodejs.org build-site script](https://github.com/nodejs/build/blob/master/setup/www/resources/scripts/build-site.sh) which is triggered by a github webhook as soon as commits are merged to master. Hopefully we'll get something similar going w/addition to zero downtime for the bot.

Any thoughts on the deployment strategy?

**Comment by Starefossen** [comment]
Personally I am a fan of container based deploys. It enables you to build the app on a different machine / service (eg. Docker Hub) and then run the new and old version side by side and gracefully routing traffic to new version.

**Comment by jbergstroem** [comment]
I'm with "whatever gets the job done". At this point downtime is not very important, but as we move forward we will need to take this into regard (lets say we need to make sure that all events from github are received).

**Comment by jbergstroem** [comment]
(I guess the benefit of the build site script is that it's already written and proved working)

**Comment by phillipj** [comment]
I just opened PR https://github.com/nodejs/build/issues/487 adding the most basic setup to get this ball rolling.

I'm all for containerizing the bot later, but for now I just want to get deploys streamlined to prevent manual work when commits are landed -- that's error-proned as shown in https://github.com/nodejs/github-bot/issues/71#issuecomment-244917295.

**Comment by phillipj** [comment]
@Starefossen any ideas on small steps towards what described earlier? Would we have to jump onto the Kubernetes wagon or could we get away with something less complex?

**Comment by Starefossen** [comment]
This depends if we want to see this with regards to running other applications like jenkins monitor, nodejs.org etc and how much uptime we want to guarantee. 

My suggestion would be to build a Docker Image for easy deployment, if this is the only application we are hosting it might be overkill with something like Kubernetes at this point.

**Comment by phillipj** [comment]
Kubernetes being overkill was my thoughts as well.

Would there be an obvious way to get zero downtime deploys if we got it
dockerized at least?

**Comment by Starefossen** [comment]
Yes, we could use something like https://github.com/jwilder/nginx-proxy

**Comment by jbergstroem** [comment]
How often have we had issues with the bot going down versus the vm/host going down? perhaps a simple process manager (or systemd) would do "for now"?

**Comment by phillipj** [comment]
@jbergstroem we don't have much insights about downtime atm, so no easy answer to those questions I'm afraid. Ideally we'd be able to visualise that in graphs, but that might a long shot. Are we doing something for this in other parts of the infra?

It's already supervised by systemd. The [github-bot service](https://github.com/nodejs/build/blob/master/setup/github-bot/resources/github-bot.service) might be improved tho, e.g. restart time of 10 secs..

Don't know if those questions was related to dockerizing or not. The reason I've been thinking about dockerizing is for deployment, not as a fix for unexpected downtime.

**Comment by phillipj** [comment]
Closing this for now as we've got a sufficient deployment "that works" without manual intervention. Not saying we can't improve deployment, if anyone wants a challenge go ahead, but its not an "issue" anymore.
