### ISSUE TITLE
feature: store jenkins job info

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/github-bot#74]
The bot currently have an endpoint that jenkins notifies on every build start/end. Since the bot is additionally moving into reading `.tap` files and likely more build info (to visualize failed tests at GH, etc), it would make sense to poll and store build data. This would make us able to create a separate frontend that can display a full build history instead of the 20 days we currently offer through github. Linking to this will make old issues/pr's not bit-rot.

**Comment by maclover7** [comment]
Available via https://nodejs-ci-health.mmarchini.me/

**Comment by maclover7** [comment]
@joyeecheung Ah, yeah, I guess that's true. If anybody wants to take this up then please feel free to reopen, though we'd have to figure out hosting for a database

**Comment by joyeecheung** [comment]
I think someone mentioned that we could use a free tier of mongodb at the collaboration summit, but I totally forgot who that was. Anyways that probably deserve a second issue with a more concrete plan.
