### ISSUE TITLE
Report what staging branches a PR can land cleanly on

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/github-bot#77]
This would be VERY useful information for backporting

**Comment by phillipj** [comment]
Huh, this sounds like a cool feature! Should it post a comment or add labels?

**Comment by addaleax** [comment]
I think labels would be good? They are pretty cheap, and maybe it’s just me but I find automated github comments by bots more noisy than helpful.

**Comment by jbergstroem** [comment]
I reckon just trying to rebase any branch against whatever branch would be pretty cheap? These doesn't have to show up in regular PR's, just one's that has a the land-on-$foo stuff?

**Comment by TheAlphaNerd** [comment]
what I would personally like to see would be automating adding the
Lts-watch labels if a commit lands cleanly on that release stream

**Comment by jbergstroem** [comment]
Oh - that would be pretty neat.

**Comment by mscdex** [comment]
Why use the `lts-watch-*` labels? Shouldn't those be added by users whether there are merge conflicts or not?

Also, how would you know which labels should be added (which branches to test), unless you mean to try all branches that are not specifically excluded via `do-not-land-on-*` labels?

Maybe a new set of labels would be best? Like `lands-cleanly-on-*` or something?
