### ISSUE TITLE
Automating PR/Issue metadata

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/github-bot#78]
We currently have templates that aids people filing issues/PR's with describing metadata:
- https://raw.githubusercontent.com/nodejs/node/master/.github/ISSUE_TEMPLATE.md
- https://raw.githubusercontent.com/nodejs/node/master/.github/PULL_REQUEST_TEMPLATE.md

Things like finding documentation, subsystem, paths to benchmark/tests in said PR should be totally feasible.

**Comment by maclover7** [comment]
Closing for now, this has large been replaced by `node-core-utils`
