### ISSUE TITLE
Missing labels

### ISSUE THREAD

**Issue by mscdex** [nodejs/github-bot#79]
I noticed that in some cases, like [this PR](https://github.com/nodejs/node/pull/8600), the bot failed to label the PR at all. It should have added the `test` label.

**Comment by sejoker** [comment]
I am curious how to check log files in case we got an error from Github. In that case, we should have a message 'Error retrieving files from GitHub' in the logs.

**Comment by mscdex** [comment]
Your guess is as good as mine. I've never tried to run my own instance of the bot before.

**Comment by jbergstroem** [comment]
We use Bunyan so logs are available on the host as well as over http (with a secret). I'm sure @phillipj can provide the access key to those that wants to fiddle.

**Comment by phillipj** [comment]
Absolutely! Just ping me on IRC and I'll give you the URL

**Comment by phillipj** [comment]
Had a look in the logs and found this:

```
[2016-09-17T11:42:06.032+02:00] ERROR: bot/15719 on server-05: Error retrieving files from GitHub (req_id=8dfe80e7-e6dd-4144-9eff-5c81afb17e88, pr=nodejs/node/#8600, action=pull_request.opened)
    err: {
      "code": 404,
      "status": "Not Found",
      "message": "{\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3\"}"
    }
```
I assume there was some inconsistencies in GitHub's side which caused this error, while trying to retrieve the files related to the mentioned PR :/

Maybe the bot should wait a couple of seconds before doing its thing, as it's not important that these labels gets added *instantaneously*.

**Comment by sejoker** [comment]
@phillipj thanks for follow up, you confirmed my initial assumption. A short timeout like you suggested would be sufficient as the first step. If necessary, more complicated setup with retry logic will need to take place.

**Comment by sejoker** [comment]
I could prepare a PR if we agree on the possible fix.

**Comment by phillipj** [comment]
@sejoker a PR would be great 👍

**Comment by sejoker** [comment]
@phillipj your feedback on https://github.com/nodejs/github-bot/issues/81 will be valuable.

**Comment by phillipj** [comment]
FYI now that @sejoker PR is merged, the bot will wait for 2 seconds before resolving labels
