### ISSUE TITLE
Ask for backport to LTS 

### ISSUE THREAD

**Issue by targos** [nodejs/github-bot#84]
After a PR is merged, ask if it should be backported or add the lts-watch label(s).

**Comment by TheAlphaNerd** [comment]
That's an awesome idea!

this could potentially be automated some what by by checking to see if a patch can land cleanly on a release branch and auto adding a label

I think it might be time to revisit the labeling itself... I'm going to put something together about this

/cc @nodejs/lts

**Comment by jbergstroem** [comment]
@TheAlphaNerd I'm not a big fan of the "use comments for chat with bot style"  -- your solution sounds great to me!

**Comment by jasnell** [comment]
+1 on automating it. The tricky thing will be the false positives -- the semver-patch commits that just happen to land cleanly despite relying on semver-minor or semver-major commits that should not be on LTS. Doc and test changes are key examples of this. If we are going to automate, then we need a better way of reliably backtracing the dependencies between PRs.

**Comment by TheAlphaNerd** [comment]
@jasnell so this is where I am thinking that we need to revisit the labels.

* lands-cleanly-vX.x
* lts-watch-vX.x
* land-vX.x

thoughts?

**Comment by jbergstroem** [comment]
I think getting labels as a first step would be a good indication. We can always revisit these PR's and checking daily/etc that they can land and pull the tags if they can't.

**Comment by jasnell** [comment]
Works for me.

**Comment by Fishrock123** [comment]
I've been talking about having the bot label it as watch if is able to land cleanly. We should be able to do this easy enough with a git clone and some basic scripting. I'll try my best to get to it next week.

**Comment by Fishrock123** [comment]
(If anyone else wants to help on another aspect, feel free to also assign yourself.)

**Comment by mscdex** [comment]
I think this can be closed now with the recent commits by @Fishrock123 right?

**Comment by targos** [comment]
I think you're right.
