### ISSUE TITLE
IRC logger

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/github-bot#85]
Just saw that http://logs.libuv.org/channels was down again (has been for 4 days). Last time it went down I suggested we could move it to the node.js infra so more people could help out keeping it going then quickly forgot about it once it was back up. This time I thought I'd bring it up here as a task that could be integrated into our bot?

**Comment by williamkapke** [comment]
Yeah- I had a convo with @piscisaureus about this at collab summit. One thing to note is that slurp is collecting logs for many channels- ie non foundation channels. We'd need to decide if the foundation is ok with supporting the others...? Or only taking on some of them...?

**Comment by phillipj** [comment]
I'm a big fan of small and focused projects, so I'd much rather have an
IRC-bot separate from the github-bot.

+1 to put such a project under governance of the github-bot team.

**Comment by piscisaureus** [comment]
The other channels are mostly stale - I would stop logging them if I cared enough.

**Comment by piscisaureus** [comment]
Sorry for the downtime :(

**Comment by phillipj** [comment]
@jbergstroem any objections against running this as a separate project / deployment? Guess we could re-use the server the bot is currently running on..

**Comment by jbergstroem** [comment]
@phillipj not at all -- it just seems to fit in this working group.

**Comment by Trott** [comment]
After 8 years, and considering that we mostly don't use IRC anymore, I think this can be closed.
