### ISSUE TITLE
Auto add `dont-land-on-v4.x` for all Inspector related commits

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodejs/github-bot#94]
The inspector is not in v4.x, so we can auto add this label. I'd be more than happy to make a contribution to this but it will be at least 2 weeks before I'll have time. If anyone else wants to pick it up that would be rad

**Comment by Fishrock123** [comment]
we could just subsystem-map this

**Comment by phillipj** [comment]
This was fixed with https://github.com/nodejs/github-bot/pull/96
