### ISSUE TITLE
Jenkins build status not visible in big PRs

### ISSUE THREAD

**Issue by phillipj** [nodejs/github-bot#97]
With https://github.com/nodejs/node/pull/9745 which has 100+ commits, we just found that the bot pushes Jenkins build status to the wrong commit SHA.

Probably because the list of commits fetched in [findLatestCommitInPr()](https://github.com/nodejs/github-bot/blob/master/lib/push-jenkins-update.js#L62) is paginated by GitHub, and therefore we'll have to do some pagination tricks to ensure we actually fetch the **latest commit** of that specific PR, even if it consists of hundreds of commits.

**Comment by jbergstroem** [comment]
ugh :/
